version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install matplotlib numpy
      - run:
          name: Dummy test (no-op)
          command: echo 'No tests implemented yet'

  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Build an artifact
          command: touch example.txt
      - store_artifacts:
          path: example.txt

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: echo 'No deployment steps implemented yet'

workflows:
  version: 2
  example:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - test
